# Generated by Django 4.2 on 2024-07-28 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.person'),
        ),
    ]
