# Generated by Django 4.2 on 2024-07-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orderdetail_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='person',
        ),
    ]
